gemfile: 'Gemfile'
PreCommit:
  # Style Check
  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop', '-a']
    on_warn: fail

  # Dependency Check
  BundleCheck:
    enabled: true
    on_warn: fail

  # Migration Check
  RailsSchemaUpToDate:
    enabled: true
    on_warn: fail

  # Checks for hard tabs in files
  HardTabs:
    enabled: true
    on_warn: fail

PrePush:
    # Unit & Integration TEST
  RSpec:
    enabled: true
    command: ['bundle', 'exec', 'rspec']
    on_warn: fail

  BundleInstall:
    enabled: true
    on_warn: fail