name: Rails CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: [ '2.6' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install SQLite (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -yqq libsqlite3-dev
      - name: Install SQLite (OSX)
        if: runner.os == 'macOs'
        run: brew install sqlite3
      - name: Install SQLite (Windows)
        if: runner.os == 'Windows'
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install sqlite
      - name: Setup Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install SQLite gem (Windows)
        if: runner.os == 'Windows'
        run: gem install sqlite3 --platform=ruby -- --with-sqlite3-include=/c:/ProgramData/ProgramData/lib/SQLite/tools
      - name: Install gems
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - name: Install packages
        run: |
          npm install
      - name: Run tests
        run: |
          bundle exec rails db:setup
          cp .env.example .env
          bundle exec rails test
        env:
          RAILS_ENV: test
